### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by amirsanni** [Yorubaname/yorubaname-website#19]
Blog link at the bottom of the page not correct.

![yorubaname combug](https://cloud.githubusercontent.com/assets/6107185/15721940/3c564562-2833-11e6-9495-1bb5f3852d3c.PNG)

**Comment by hayzedious** [comment]
@dadepo I noticed an inconsistency after i pulled the project to my local system, i checked up the blog link on my local copy and it was prefixed with 'http://' but on the remote site, no such prefix is present

**Comment by dadepo** [comment]
@hayzedious You are correct. I almost forgot about the state of this issue. It has actually been fixed. But not just deployed yet. So yes, your local copy would not have the problem.

I will keep this ticket open and only close it when we deploy.

**Comment by hayzedious** [comment]
OK cool

**Comment by dadepo** [comment]
Deployed!
