### ISSUE TITLE
Category: Workshop

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-website#28]
Let's create a category, accessible to the user via the front end, called "workshop". Perhaps, also, create a button in the back end with a check mark that the lexicographer can tick to ensure that an entry shows up on the workshop front end.

The purpose of this "workshop" category is for names whose meanings/tone marking aren't clear, and for which we need help. So the competent user visiting the dictionary for the first time knows where to go if he/she wants to help without becoming a full-time or part-time lexicographer.

**Comment by dadepo** [comment]
How is this feature request different from https://github.com/Yorubaname/yorubaname-website/issues/24
Apart from the terminology (i.e Workshop category) it seems to be serving the same purpose. Or you envision this to be different in anyway? if no, then we can close this and mark it as a duplicate issue.

**Comment by kolatubosun** [comment]
Yea, it's the same. I had forgotten about that one you filed earlier. There's a slight difference though: this one will have a check box feature on the back end with which the lexicographer can, without effort, mark an entry as incomplete in meaning.

**Comment by dadepo** [comment]
Maybe there is no need to have the button in the backend? Any entry that is "incomplete" would automatically appear. Removing the need to have an extra step of having someone click a button before these names appear as in need of some attention by people who might be able to help

**Comment by kolatubosun** [comment]
Okay, but what marks something as "incomplete"? For me, even if a name doesn't have "famous people" or "variant", it can still be complete. How do we train the app to know which names to put in the "incomplete" group?

**Comment by dadepo** [comment]
We have this feature: completion indicator, already added https://github.com/Yorubaname/yorubaname-website/issues/3.

We can hook that into this issue. We can use the completion indicator to decide what the threshold is for a name to automatically appear as incomplete.

**Comment by kolatubosun** [comment]
Oh okay. Lovely.

But, going forward, I'm really interested in checkboxes as means of doing
some of the things we currently have to type out. From my experience
working on the name entries everyday, I've realised that some of what I do
are repititive, and takes too much good time. For instance, if a name
doesn't have its meaning and we want to publish it (I'm in favour of this),
instead of writing "Name unknown", I just want to check a box. And this
checking prompts the app to display "name unknown" in the front end. Along
with an "suggest meaning" button. Also, if the meaning we have of the name
is one we're not absolutely sure of, I don't want to have to write
"verification needed" as I currently do. I'd want to check a box that
displays that "verification needed" on the homepage, along with "If you
know any other way this name can be interpreted, click here to suggest it".
Also, for "àmútọ̀runwá" names, I just want a check box under the "Extra
Information about this Name", and have it show "Amutorunwa" on the front
end. In short, completing entries in the back end could be way more
simplified, and make it easy for those working on it. Some things will
absolutely need typing (e.g. meanings, etymology, pronunciation, etc), but
some don't, and currently slow us down.




 ------------

[image: Kola Tubosun on about.me]

*Kólá Túbòsún*
about.me/kola_tubosun
  <http://about.me/kola_tubosun>Support our dictionary project at
http://igg.me/at/YorubaName/x/9532548

**Comment by dadepo** [comment]
You have conflated a lot of things in this thread which is not really related to the issue that started this discussion. 

I would say you create separate issues to address the things you have mentioned.

The various features I can see in your response include:

1. Add a button to automatically add "verification needed" to a name (you can add another issue and then expand the details of this request)
2.  Add a feature to easily tag names that are "àmútọ̀runwá" (add another issue and expand on the details in there)

The one about Typing Meaning Unknown should not be necessary. What is needed is to modify the dashboard to be able to publish a name without filling in the meaning entry. So you can add a third issue:

3. Modify dashboard to support publishing a name without supplying the meaning field (then expand the details in the description, why it is needed etc etc.)

This would make for easier management of issues if we have distinct issues for the various changes we want, and under these issues we can discuss them separately.

Ps: Replying to the discussion from within gmail is not really the best as it does not show up that nice on github.

**Comment by dadepo** [comment]
I would close this issue now and update issue https://github.com/Yorubaname/yorubaname-website/issues/24 to reflect its implementation should take note of the completion indicator feature described here https://github.com/Yorubaname/yorubaname-website/issues/3
