### ISSUE TITLE
Google Integration Possible?

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-website#30]
Laila mentioned something last week which I thought was interesting. Google Translate already has thousands of Yorùbá words and their translations. So, instead of re-inventing the wheel, is there a way we can benefit from their work? I'm thinking we integrate that Translate app into the dictionary some way. 

How I assume it will work is that the lexicographer will only have to fill in the morphology field (e.g. ade-bá-ire) in the back end and Google Translate will fill out the gloss from its own database.(e.g. ade=crown, bá=meet, ire=goodness)

My question is whether it is doable. For one, we don't know if Google has their database in a publicly accessible place. Should we ask them if this integration is possible?

**Comment by dadepo** [comment]
In general it is possible. The Google Translate API is available, but it is not free...it is a paid service. This page gives an overview of the pricing https://cloud.google.com/translate/v2/pricing

**Comment by dadepo** [comment]
"$20 per 1 million characters of text" sounds like something within budget.

**Comment by kolatubosun** [comment]
Nice. Something to think about in the future. We don't need to commit to it now, especially since it will take some modifications to the codebase to achieve.

**Comment by dadepo** [comment]
Cool. I would close this issue then. I also added the "question" label to it.

**Comment by dadepo** [comment]
I also removed the "Assignment" to me and @hardcorekancil . (for this and other issues). I think it might be misinterpreted by people who wants to pick up an issue, to mean those issues with people already assigned to them are already working on fixing the issue or implementing the feature - which is not the case.
I think we can use `@username` to get the attention of someone instead of using the assign.

**Comment by kolatubosun** [comment]
Okay. I just didn't know if you'd see if it if I didn't assign it. Will adjust in the future.
