### ISSUE TITLE
Can We Disable Syllable Breakdown as a Compulsory Field?

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-website#31]
Our conceptualisation of this field is to guide the TTS system. But as we haven't launched that feature, I'd ask that we make the Syllable Breakdown field optional for now. It currently just slows down work and discourages new Lexicographers.

**Comment by dadepo** [comment]
Fixed merged to codebase. Ticket will be closed as soon as it is deployed.

**Comment by kolatubosun** [comment]
Yay.

**Comment by dadepo** [comment]
Deployed

**Comment by kolatubosun** [comment]
Sorry one more thing: we forgot to remove the "required" sign written in red above it, so people aren't confused.

**Comment by dadepo** [comment]
Yeah...just saw this...removing it right away

**Comment by kolatubosun** [comment]
(y)

**Comment by dadepo** [comment]
Removed and deployed
