### ISSUE TITLE
Facebook LikePlugin Has Disappeared

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-website#33]
@dadepo In this space where "Yoruba Names Dictionary" is written at the bottom of the page is a plugin that allows people to "like" our Facebook page directly
![screenshot 32](https://cloud.githubusercontent.com/assets/18510601/16764767/125e9114-4828-11e6-906a-2162a8052755.png)
 from the site. The plugin is gone.

**Comment by dadepo** [comment]
Fixed

**Comment by dadepo** [comment]
Maybe not. gives an error when you try to share via the plugin

> App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

 @temiyemi can you help look into this? Should be a quick one

**Comment by dadepo** [comment]
@kolatubosun or it might be something you can resolve. Looks like a setting issue within the facebook app?

**Comment by kolatubosun** [comment]
I can make you a FB admin. I don't know what to do.

**Comment by kolatubosun** [comment]
Done.

**Comment by dadepo** [comment]
Shows me as an "Editor" not an "Admin"

**Comment by kolatubosun** [comment]
Fixed.

**Comment by dadepo** [comment]
When generating the code for the FB Page plugin, I see it needs to be associated with an App Id. @temiyemi  When you generated the code, you associated it with an App that is still in dev mode. Can you make this app public and add either Kola or myself as an Admin? 
Danke!

**Comment by temiyemi** [comment]
I didn’t create a Facebook app. You already had a Facebook Like widget on the Yoruba Names Blog, so I simply copied the parameters over to the front end website the other time.

Someone must have created the app/page on Facebook, and s/he is the Admin who can fix it.

Yemi

**Comment by dadepo** [comment]
Fixed

**Comment by kolatubosun** [comment]
Yay.
