### ISSUE TITLE
Add Sample Data to the Embedded Database

### ISSUE THREAD

**Issue by adedayoominiyi** [Yorubaname/yorubaname-website#35]
Add some sample data (complete and partial) to the embedded HSQLDB database to allow new developers get a real feel for the system.

**Comment by adedayoominiyi** [comment]
It seems also adding sample data to the elasticsearch component would go a long way to help onboard new developers

**Comment by dadepo** [comment]
Commit d5575d2 ensures ElasticSearch is initialised with some sample data.
