### ISSUE TITLE
Switch Implementation Of Latest Searches, Latest Addition and Most Popular to use database

### ISSUE THREAD

**Issue by dadepo** [Yorubaname/yorubaname-website#40]
Currently the implementation of Latest Searches, Latest Addition and Most Popular keeps the information all in memory. Meaning on restart this data would be lost. 

Change implementation to use a datastore. Related to #39

**Comment by Zifah** [comment]
This issues has been resolved in the new repo.

Pull request: https://github.com/Yorubaname/YorubaNameDictionary/pull/112
