### ISSUE TITLE
License for open source project

### ISSUE THREAD

**Issue by mmalaquiasdev** [Yorubaname/yorubaname-website#63]
Hello,

As i understand this project can be trully open source, but need License for that.

What do you think about use a License like MIT or Apache?

**Comment by dadepo** [comment]
Thanks for bringing this up. We have actually had discussions about which license to go with within the team at some point, but I guess we dropped the ball a lil' bit in the rush to go to production. 

The discussion has resumed and soon enough, we would update with a license.

**Comment by nonthevisor** [comment]
I see this issue was closed, but as of today, I still can find no license in the repo. Could you please add one, so it is clear if and how this code can be used?
