### ISSUE TITLE
Refactoring lambda code style

### ISSUE THREAD

**Issue by mmalaquiasdev** [Yorubaname/yorubaname-website#72]
If we have a lambda expression with one line of code, like this:

```
feedbacks.stream().forEach(feedback -> {
            feedbackRepository.delete(feedback);
});
```
We can simplify the code, just remove the keys {...}, like this:

```
feedbacks.stream().forEach(feedback -> feedbackRepository.delete(feedback));
```
The gain is to have an easier code to read.

**Comment by mmalaquiasdev** [comment]
#74

**Comment by Kaperskyguru** [comment]
please i need a clear picture of what is required to be done...

**Comment by mmalaquiasdev** [comment]
Hi, dude... i just finish this issue with a pr #74, you can see the changes in:

https://github.com/Yorubaname/yorubaname-website/pull/74/commits/e0f08ce657a3ff5f80dca664a57f5e78578abfee

and 

https://github.com/Yorubaname/yorubaname-website/pull/74/commits/a1029754efb81bde5eb37ae21bfd153ce3093858

**Comment by Kaperskyguru** [comment]
ok... seen... any issue
