### ISSUE TITLE
"Pronunciation" spelling

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-website#75]
I noticed this just a few days ago. Must have been there for a while.
What you see right beside the audio sign when you open a name entry is "pronounciation". It's the wrong but commonly mistaken spelling. It should be "pronunciation". 

The related issue is the size of the audio icon. We already discussed this one. I'm wondering if, after we unveil the female voice, we can just use colours to code each gender: a blue speaker icon for male, a pink one for female. But all of them on the same level as the name (as we have it in Webster and Dictionary.com, photo attached), not under it as we currently do.

Means that both "pronounciation" and "pronunciation" can disappear for good.

![screenshot 513](https://user-images.githubusercontent.com/18510601/32176099-018b9b54-bd87-11e7-94bc-41344f163bce.png)
![screenshot 512](https://user-images.githubusercontent.com/18510601/32176101-01b649c6-bd87-11e7-8618-3de94d907522.png)

**Comment by kolatubosun** [comment]
What can be done immediately is to change "pronounciation" to "pronunciation". cc: @netblaiz

**Comment by netblaiz** [comment]
Exactly

**Comment by netblaiz** [comment]
I will fork the repo tonight and see to making the changes

**Comment by dadepo** [comment]
The spelling has been updated in this commit 68ba4e43c2294eef262364182525d7840c7a8805
Would be live on next deploy.
